# Generated by Django 4.2.2 on 2023-11-01 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_friendship_delete_frindship"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="receiver",
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.userprofile"
            ),
        ),
        migrations.CreateModel(
            name="ChatChannel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_dm", models.BooleanField(default=False)),
                ("members", models.ManyToManyField(to="accounts.userprofile")),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="chat_channel",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.chatchannel",
            ),
            preserve_default=False,
        ),
    ]
