# Generated by Django 4.2.2 on 2023-11-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_remove_message_receiver_alter_message_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatchannel",
            name="title",
            field=models.CharField(default="DM", max_length=75),
        ),
    ]
