# Generated by Django 4.2.2 on 2023-11-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_chatchannel_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatchannel",
            name="title",
            field=models.CharField(default="channel", max_length=75),
        ),
    ]
