# Generated by Django 4.2.2 on 2023-11-01 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_friendship_delete_frindship"),
        ("chat", "0004_alter_chatchannel_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.userprofile"
            ),
        ),
    ]
