# Generated by Django 4.2.2 on 2023-11-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_alter_message_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatchannel",
            name="is_changed",
            field=models.BooleanField(default=False),
        ),
    ]
