# Generated by Django 4.2.2 on 2023-11-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_chatchannel_is_changed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatchannel",
            name="is_changed",
        ),
        migrations.AddField(
            model_name="message",
            name="is_changed",
            field=models.BooleanField(default=False),
        ),
    ]
