# Generated by Django 4.2.6 on 2023-10-30 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_customuser_email_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="user_uuid",
        ),
    ]
