# Generated by Django 4.2.6 on 2023-10-30 22:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_frindship_customuser_created_at_userprofile_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="frindship",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="frindship",
            name="receiver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver",
                to="accounts.userprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="frindship",
            name="sender",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender",
                to="accounts.userprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="frindship",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "accepted"),
                    ("waiting", "waiting"),
                    ("rejected", "rejected"),
                ],
                default=1,
                max_length=8,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="frindship",
            name="updated_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
