# Generated by Django 4.2.6 on 2023-10-31 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_frindship_receiver_alter_frindship_sender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frindship",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver",
                to="accounts.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="frindship",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender",
                to="accounts.userprofile",
            ),
        ),
    ]
