# Generated by Django 4.2.6 on 2023-10-31 02:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0012_alter_frindship_receiver_alter_frindship_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(default=1, upload_to="profiles/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="friends",
            field=models.ManyToManyField(
                blank=True, related_name="friends", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
