# Generated by Django 4.2.6 on 2023-10-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_userprofile_picture_alter_userprofile_friends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(default="profiles/", upload_to="profiles/"),
        ),
    ]
