# Generated by Django 4.2.6 on 2023-10-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_alter_userprofile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(
                default="profiles/default.png", upload_to="profiles/"
            ),
        ),
    ]
